pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS_ID = 'bd973968-8384-4243-bd5d-610a69ffecb5'
        DOCKERHUB_REPO = 'jommi123/language-project'
    }

    stages {
        stage('Tests') {
            steps {
                script {
                    dir('backend/tests') {
                        bat 'npm install'
                        bat 'npm test'
                        bat 'npm run test:jest authmiddleware.test.js'
                    }
                }
            }
        }
        stage('Build and Push Images') {
            steps {
                script {
                    // build and push the client image
                    dir('language-learning-app') {
                        docker.build("${DOCKERHUB_REPO}:latestclient")
                        docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                            docker.image("${DOCKERHUB_REPO}:latestclient").push()
                        }
                    }

                    // nuild and push the server image
                    dir('backend') {
                        docker.build("${DOCKERHUB_REPO}:latestserver")
                        docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                            docker.image("${DOCKERHUB_REPO}:latestserver").push()
                        }
                    }
                }
            }
        }
    }
}
